apiVersion: apps/v1
kind: Deployment
metadata:
  name: gittrack
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gittrack
  template:
    metadata:
      labels:
        name: gittrack
    spec:
      serviceAccountName: gittrack
      containers:
        - name: gittrack
          # Replace this with the built image name
          image: docker.io/qiell/gittrack:latest
          command:
          - gittrack
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gittrack"
